stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - master

push:
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
    - docker push $IMAGE_NAME:latest
  only:
    - master
