image: docker:20.10.7

stages:
  - build
  - push

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - main
    - CI-CD
  tags:
    - private-runner

push:
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $IMAGE_NAME:latest
  only:
    - main
    - CI-CD
  tags:
    - private-runner
