image: docker:20.10.7

stages:
  - build
  - push

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - master
    - CI-CD
  tags:
    - comp2120

push:
  stage: push
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD -e $DOCKER_HUB_EMAIL
    - docker push $IMAGE_NAME:latest
  only:
    - master
    - CI-CD
  tags:
    - comp2120
